# Generated by Django 2.2.5 on 2019-09-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190909_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='display_image',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
    ]
