# Generated by Django 2.2.5 on 2019-09-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190913_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-end_date'], 'verbose_name_plural': 'Projects'},
        ),
    ]
