# Generated by Django 2.2.5 on 2019-09-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190913_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
