# Generated by Django 2.2.5 on 2019-09-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190914_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
