# Generated by Django 2.2.5 on 2019-09-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
