# Generated by Django 2.2.5 on 2019-09-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190913_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
