# Generated by Django 2.2.5 on 2019-09-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_profile_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('recommendation', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('linkedin', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='info.Profile')),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
