# Generated by Django 2.2.5 on 2019-09-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_philosophy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='philosophy',
            options={'verbose_name_plural': 'philosophies'},
        ),
        migrations.AddField(
            model_name='philosophy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
