# Generated by Django 2.2.5 on 2019-09-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20190909_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, upload_to='clients/'),
        ),
        migrations.AlterField(
            model_name='philosophy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='philosophy/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
