# Generated by Django 2.2.5 on 2019-09-13 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20190909_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-from_date'], 'verbose_name_plural': 'Experiences'},
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='accomplishments/%Y')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accomplishments', to='info.Profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
