# Generated by Django 2.2.5 on 2019-09-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20190913_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accomplishment',
            new_name='Achievement',
        ),
    ]
