# Generated by Django 2.2.5 on 2019-09-14 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20190913_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='document',
            field=models.FileField(blank=True, default='defaults/default_achievements.jpg', null=True, upload_to='achievements/%Y'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='info.Profile'),
        ),
    ]
