# Generated by Django 2.2.5 on 2019-09-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20190914_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='achievements/%Y'),
        ),
    ]
